// Commands module - contains all CLI command implementations

pub mod add;
pub mod branch;
pub mod cat_object;
pub mod checkout;
pub mod clone;
pub mod commit;
pub mod diff;
pub mod fetch;
pub mod hash_object;
pub mod init;
pub mod log;
pub mod login;
pub mod logout;
pub mod ls_tree;
pub mod merge;
pub mod pull;
pub mod push;
pub mod remote;
pub mod restore;
pub mod rev_parse;
pub mod show;
pub mod status;
pub mod verify_pack;
pub mod whoami;

pub use add::cmd_add;
pub use branch::cmd_branch;
pub use cat_object::cmd_cat_object;
pub use checkout::{cmd_checkout, cmd_checkout_files};
pub use clone::cmd_clone;
pub use commit::cmd_commit;
pub use diff::cmd_diff;
pub use fetch::cmd_fetch;
pub use hash_object::cmd_hash_object;
pub use init::cmd_init;
pub use log::{cmd_log, cmd_log_oneline};
pub use login::cmd_login;
pub use logout::cmd_logout;
pub use ls_tree::cmd_ls_tree;
pub use merge::cmd_merge;
// cmd_merge_abort is called directly via commands::merge::cmd_merge_abort() in main.rs
pub use pull::cmd_pull;
pub use push::cmd_push;
pub use remote::{cmd_remote_add, cmd_remote_list, cmd_remote_remove, cmd_remote_rename, cmd_remote_set_url};
pub use restore::cmd_restore;
pub use rev_parse::cmd_rev_parse;
pub use show::cmd_show;
pub use status::cmd_status;
pub use verify_pack::cmd_verify_pack;
pub use whoami::cmd_whoami;
